<?php

namespace Database\Seeders;

use App\Models\Ciudad;
use Illuminate\Database\Seeder;

class CiudadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ciudades = [
            'ARICA',
            'CAMARONES',
            'PUTRE',
            'GENERAL LAGOS',
            'IQUIQUE',
            'ALTO HOSPICIO',
            'POZO ALMONTE',
            'CAMIÑA',
            'COLCHANE',
            'HUARA',
            'PICA',
            'ANTOFAGASTA',
            'MEJILLONES',
            'SIERRA GORDA',
            'TALTAL',
            'CALAMA',
            'OLLAGÜE',
            'SAN PEDRO DE ATACAMA',
            'TOCOPILLA',
            'MARÍA ELENA',
            'COPIAPÓ',
            'CALDERA',
            'TIERRA AMARILLA',
            'CHAÑARAL',
            'DIEGO DE ALMAGRO',
            'VALLENAR',
            'ALTO DEL CARMEN',
            'FREIRINA',
            'HUASCO',
            'LA SERENA',
            'COQUIMBO',
            'ANDACOLLO',
            'LA HIGUERA',
            'PAIGUANO',
            'VICUÑA',
            'ILLAPEL',
            'CANELA',
            'LOS VILOS',
            'SALAMANCA',
            'OVALLE',
            'COMBARBALÁ',
            'MONTE PATRIA',
            'PUNITAQUI',
            'RÍO HURTADO',
            'VALPARAÍSO',
            'CASABLANCA',
            'CONCÓN',
            'JUAN FERNÁNDEZ',
            'PUCHUNCAVÍ',
            'QUILPUÉ',
            'QUINTERO',
            'VILLA ALEMANA',
            'VIÑA DEL MAR',
            'ISLA DE PASCUA',
            'LOS ANDES',
            'CALLE LARGA',
            'RINCONADA',
            'SAN ESTEBAN',
            'LA LIGUA',
            'CABILDO',
            'PAPUDO',
            'PETORCA',
            'ZAPALLAR',
            'QUILLOTA',
            'CALERA',
            'LA CALERA',
            'HIJUELAS',
            'LA CRUZ',
            'LIMACHE',
            'NOGALES',
            'OLMUÉ',
            'SAN ANTONIO',
            'ALGARROBO',
            'CARTAGENA',
            'EL QUISCO',
            'EL TABO',
            'SANTO DOMINGO',
            'SAN FELIPE',
            'CATEMU',
            'LLAILLAY',
            'PANQUEHUE',
            'PUTAENDO',
            'SANTA MARÍA',
            'RANCAGUA',
            'CODEGUA',
            'COINCO',
            'COLTAUCO',
            'DOÑIHUE',
            'GRANEROS',
            'LAS CABRAS',
            'MACHALÍ',
            'MALLOA',
            'MOSTAZAL',
            'OLIVAR',
            'PEUMO',
            'PICHIDEGUA',
            'QUINTA DE TILCOCO',
            'RENGO',
            'REQUÍNOA',
            'SAN VICENTE',
            'PICHILEMU',
            'LA ESTRELLA',
            'LITUECHE',
            'MARCHIHUE',
            'NAVIDAD',
            'PAREDONES',
            'SAN FERNANDO',
            'CHÉPICA',
            'CHIMBARONGO',
            'LOLOL',
            'NANCAGUA',
            'PALMILLA',
            'PERALILLO',
            'PLACILLA',
            'PUMANQUE',
            'SANTA CRUZ',
            'TALCA',
            'CONSTITUCIÓN',
            'CUREPTO',
            'EMPEDRADO',
            'MAULE',
            'PELARCO',
            'PENCAHUE',
            'RÍO CLARO',
            'SAN CLEMENTE',
            'SAN RAFAEL',
            'CAUQUENES',
            'CHANCO',
            'PELLUHUE',
            'CURICÓ',
            'HUALAÑÉ',
            'LICANTÉN',
            'MOLINA',
            'RAUCO',
            'ROMERAL',
            'SAGRADA FAMILIA',
            'TENO',
            'VICHUQUÉN',
            'LINARES',
            'COLBÚN',
            'LONGAVÍ',
            'PARRAL',
            'RETIRO',
            'SAN JAVIER',
            'VILLA ALEGRE',
            'YERBAS BUENAS',
            'CONCEPCIÓN',
            'CORONEL',
            'CHIGUAYANTE',
            'FLORIDA',
            'HUALQUI',
            'LOTA',
            'PENCO',
            'SAN PEDRO DE LA PAZ',
            'SANTA JUANA',
            'TALCAHUANO',
            'TOMÉ',
            'HUALPÉN',
            'LEBU',
            'ARAUCO',
            'CAÑETE',
            'CONTULMO',
            'CURANILAHUE',
            'LOS ÁLAMOS',
            'TIRÚA',
            'LOS ÁNGELES',
            'ANTUCO',
            'CABRERO',
            'LAJA',
            'MULCHÉN',
            'NACIMIENTO',
            'NEGRETE',
            'QUILACO',
            'QUILLECO',
            'SAN ROSENDO',
            'SANTA BÁRBARA',
            'TUCAPEL',
            'YUMBEL',
            'ALTO BIOBÍO',
            'CHILLÁN',
            'BULNES',
            'COBQUECURA',
            'COELEMU',
            'COIHUECO',
            'CHILLÁN VIEJO',
            'EL CARMEN',
            'NINHUE',
            'ÑIQUÉN',
            'PEMUCO',
            'PINTO',
            'PORTEZUELO',
            'QUILLÓN',
            'QUIRIHUE',
            'RÁNQUIL',
            'SAN CARLOS',
            'SAN FABIÁN',
            'SAN IGNACIO',
            'SAN NICOLÁS',
            'TREGUACO',
            'YUNGAY',
            'TEMUCO',
            'CARAHUE',
            'CUNCO',
            'CURARREHUE',
            'FREIRE',
            'GALVARINO',
            'GORBEA',
            'LAUTARO',
            'LONCOCHE',
            'MELIPEUCO',
            'NUEVA IMPERIAL',
            'PADRE LAS CASAS',
            'PERQUENCO',
            'PITRUFQUÉN',
            'PUCÓN',
            'SAAVEDRA',
            'TEODORO SCHMIDT',
            'TOLTÉN',
            'VILCÚN',
            'VILLARRICA',
            'CHOLCHOL',
            'ANGOL',
            'COLLIPULLI',
            'CURACAUTÍN',
            'ERCILLA',
            'LONQUIMAY',
            'LOS SAUCES',
            'LUMACO',
            'PURÉN',
            'RENAICO',
            'TRAIGUÉN',
            'VICTORIA',
            'VALDIVIA',
            'CORRAL',
            'LANCO',
            'LOS LAGOS',
            'MÁFIL',
            'MARIQUINA',
            'PAILLACO',
            'PANGUIPULLI',
            'LA UNIÓN',
            'FUTRONO',
            'LAGO RANCO',
            'RÍO BUENO',
            'PUERTO MONTT',
            'CALBUCO',
            'COCHAMÓ',
            'FRESIA',
            'FRUTILLAR',
            'LOS MUERMOS',
            'LLANQUIHUE',
            'MAULLÍN',
            'PUERTO VARAS',
            'CASTRO',
            'ANCUD',
            'CHONCHI',
            'CURACO DE VÉLEZ',
            'DALCAHUE',
            'PUQUELDÓN',
            'QUEILÉN',
            'QUELLÓN',
            'QUEMCHI',
            'QUINCHAO',
            'OSORNO',
            'PUERTO OCTAY',
            'PURRANQUE',
            'PUYEHUE',
            'RÍO NEGRO',
            'SAN JUAN DE LA COSTA',
            'SAN PABLO',
            'CHAITÉN',
            'FUTALEUFÚ',
            'HUALAIHUÉ',
            'PALENA',
            'COYHAIQUE',
            'LAGO VERDE',
            'AYSÉN',
            'PUERTO AYSÉN',
            'CISNES',
            'PUERTO CISNES',
            'GUAITECAS',
            'COCHRANE',
            'O’HIGGINS',
            'TORTEL',
            'CHILE CHICO',
            'RÍO IBÁÑEZ',
            'PUNTA ARENAS',
            'LAGUNA BLANCA',
            'RÍO VERDE',
            'SAN GREGORIO',
            'CABO DE HORNOS (EX - NAVARINO)',
            'ANTÁRTICA',
            'PORVENIR',
            'PRIMAVERA',
            'TIMAUKEL',
            'NATALES',
            'PUERTO NATALES',
            'TORRES DEL PAINE',
            'SANTIAGO',
            'CERRILLOS',
            'CERRO NAVIA',
            'CONCHALÍ',
            'EL BOSQUE',
            'ESTACIÓN CENTRAL',
            'HUECHURABA',
            'INDEPENDENCIA',
            'LA CISTERNA',
            'LA FLORIDA',
            'LA GRANJA',
            'LA PINTANA',
            'LA REINA',
            'LAS CONDES',
            'LO BARNECHEA',
            'LO ESPEJO',
            'LO PRADO',
            'MACUL',
            'MAIPÚ',
            'ÑUÑOA',
            'PEDRO AGUIRRE CERDA',
            'PEÑALOLÉN',
            'PROVIDENCIA',
            'PUDAHUEL',
            'QUILICURA',
            'QUINTA NORMAL',
            'RECOLETA',
            'RENCA',
            'SAN JOAQUÍN',
            'SAN MIGUEL',
            'SAN RAMÓN',
            'VITACURA',
            'PUENTE ALTO',
            'PIRQUE',
            'SAN JOSÉ DE MAIPO',
            'COLINA',
            'LAMPA',
            'TILTIL',
            'SAN BERNARDO',
            'BUIN',
            'CALERA DE TANGO',
            'PAINE',
            'MELIPILLA',
            'ALHUÉ',
            'CURACAVÍ',
            'MARÍA PINTO',
            'SAN PEDRO',
            'TALAGANTE',
            'EL MONTE',
            'ISLA DE MAIPO',
            'PADRE HURTADO',
            'PEÑAFLOR',
        ];

        foreach ($ciudades as $nombre) {
            Ciudad::query()->updateOrCreate(
                ['nombre' => $nombre],
                ['activo' => true],
            );
        }
    }
}
